import { Link } from "react-router";
import { Button } from "@/components/ui/button";
import { Zap, ArrowRight } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-md">
        <div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-6">
          <Link to="/" className="flex items-center gap-2 font-semibold text-sm">
            <Zap className="h-5 w-5 text-primary" />
            NoirOps
          </Link>
          <div className="flex items-center gap-3">
            <Link to="/auth">
              <Button variant="ghost" size="sm">Sign In</Button>
            </Link>
            <Link to="/auth">
              <Button size="sm" className="gap-1">Get Started <ArrowRight className="h-3.5 w-3.5" /></Button>
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-20">
        <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="prose prose-sm max-w-none space-y-6 text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>
              By accessing or using NoirOps ("the Service"), you agree to be bound by these 
              Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">2. Description of Service</h2>
            <p>
              NoirOps is an AI-powered content intelligence platform that helps creators 
              and entrepreneurs discover trends, generate content, plan publishing schedules, 
              and analyze content activity. The Service is currently in beta and is provided 
              free of charge.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">3. Account Registration</h2>
            <p>
              You may access the Service using email authentication or as a guest user. 
              You are responsible for maintaining the confidentiality of your account and 
              for all activities under your account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">4. Your Content</h2>
            <p>
              You retain ownership of all content you create, upload, or generate through 
              NoirOps. By using the Service, you grant us a limited license to store and 
              process your content as necessary to provide the Service.
            </p>
            <p>
              We do not use your content to train AI models or share it with third parties 
              without your explicit consent.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">5. AI-Generated Content</h2>
            <p>
              Content generated by NoirOps' AI features is provided as a starting point. 
              You are responsible for reviewing, editing, and approving any AI-generated 
              content before publishing. We do not guarantee the accuracy, originality, or 
              legal compliance of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to the Service or other users' accounts</li>
              <li>Interfere with or disrupt the Service</li>
              <li>Use the Service to generate content that is harmful, deceptive, or violates others' rights</li>
              <li>Resell or redistribute the Service without authorization</li>
              <li>Use automated tools to access the Service except through our provided APIs</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">7. Beta Disclaimer</h2>
            <p>
              NoirOps is currently in beta. The Service may contain bugs, inaccuracies, or 
              incomplete features. We make no warranties about the reliability, availability, 
              or performance of the Service during the beta period.
            </p>
            <p>
              During beta, all features are provided free of charge. We reserve the right to 
              modify, limit, or discontinue any feature at any time.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, NoirOps and its affiliates shall not 
              be liable for any indirect, incidental, special, consequential, or punitive 
              damages resulting from your use of or inability to use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">9. Termination</h2>
            <p>
              You may stop using the Service at any time. We may suspend or terminate your 
              access if you violate these terms. Upon termination, your right to use the 
              Service ceases, and we will make your data available for export for a 
              reasonable period.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">10. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. We will notify you of material 
              changes. Your continued use of the Service after changes constitutes acceptance 
              of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">11. Contact</h2>
            <p>
              Questions about these terms? Contact us at{" "}
              <a href="mailto:legal@noiroops.com" className="text-primary hover:underline">
                legal@noiroops.com
              </a>
              {" "}or through our{" "}
              <Link to="/contact" className="text-primary hover:underline">contact page</Link>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-border/50 mt-20">
        <div className="mx-auto max-w-6xl px-6 py-8 flex items-center justify-between">
          <div className="flex items-center gap-2 font-semibold text-sm">
            <Zap className="h-5 w-5 text-primary" />
            NoirOps
          </div>
          <div className="flex gap-4 text-xs text-muted-foreground">
            <Link to="/about" className="hover:text-foreground transition-colors">About</Link>
            <Link to="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link to="/contact" className="hover:text-foreground transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
